# Generated by Django 5.2.15 on 2026-06-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_blog_contact_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='education',
            name='year',
            field=models.IntegerField(max_length=50),
        ),
    ]
