# Generated by Django 5.2.15 on 2026-06-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='desc',
            field=models.TextField(default=False, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('resume', 'Resume'), ('certificate', 'Certificate')], default=True, max_length=20),
            preserve_default=False,
        ),
    ]
