# Generated by Django 5.2.15 on 2026-06-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_document_desc_document_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='desc',
            field=models.TextField(),
        ),
    ]
