# Generated by Django 5.2.15 on 2026-06-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_document_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='desc',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
