# Generated by Django 5.2.15 on 2026-06-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_document_desc_alter_document_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
