# Generated by Django 5.2.15 on 2026-07-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_document_is_active_document_preview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
