# Generated by Django 5.2.15 on 2026-07-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_contact_twitter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('caption', models.TextField()),
                ('image', models.ImageField(upload_to='journey/')),
                ('event_date', models.DateField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
