# Generated by Django 5.2.15 on 2026-07-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_journey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='journey',
            name='image',
            field=models.ImageField(upload_to='journey/'),
        ),
    ]
