# Generated by Django 5.2.15 on 2026-07-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_remove_journey_created_at_alter_journey_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='show_on_homepage',
            field=models.BooleanField(default=True, verbose_name='Show on homepage'),
        ),
        migrations.AddField(
            model_name='project',
            name='show_on_homepage',
            field=models.BooleanField(default=True, verbose_name='Show on homepage'),
        ),
    ]
