# Generated by Django 5.2.15 on 2026-07-09 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_skillcategory_skill_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.DeleteModel(
            name='SkillCategory',
        ),
    ]
