# Generated by Django 5.2.15 on 2026-07-16 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_skillcategory_skill_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact Info', 'verbose_name_plural': 'Contact Info'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Education', 'verbose_name_plural': 'Education'},
        ),
        migrations.AlterModelOptions(
            name='journey',
            options={'verbose_name': 'Journey Highlights', 'verbose_name_plural': 'Journey Highlights'},
        ),
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'ordering': ['order'], 'verbose_name': 'Skill Category', 'verbose_name_plural': 'Skill Categories'},
        ),
    ]
