# Generated by Django 5.2.15 on 2026-07-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_alter_contact_options_alter_education_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='year',
            new_name='from_year',
        ),
        migrations.AddField(
            model_name='education',
            name='to_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
