# Generated by Django 5.2.15 on 2026-07-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_intro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Intro',
        ),
    ]
