# Generated by Django 5.2.15 on 2026-07-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_introduction_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='introduction',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='intro_photos/'),
        ),
    ]
